### ISSUE TITLE
Version 1.0.9 returns a ##[error][ERROR]:Only absolute URLs are supported

### ISSUE THREAD

**Issue by Msanzdelrio** [GeopJr/action-accessibility#10]
When configuring for 1.0.9 version, the action always returns a:

##[error][ERROR]:Only absolute URLs are supported

**Comment by GeopJr** [comment]
Judging by the above response, I believe the problem is here: https://github.com/GeopJr/action-accessibility/blob/main/index.js#L99

GoFile didn't return ok. I should stop the action rather than return false. (Their API might have been offline at that time).

**Comment by Msanzdelrio** [comment]
lovely! thank you!!
